import image from './chama-con-naranja.png'
export const sliderItems = [
    {
      id: 1,
      img: image,
      title: "SUMMER SALE",
      desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "f5fafd",
    },
    {
      id: 2,
      img: image,
      title: "AUTUMN COLLECTION",
      desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "fcf1ed",
    },
    {
      id: 3,
      img: image,
      title: "LOUNGEWEAR LOVE",
      desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "fbf0f4",
    },
  ];

  export const categories = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      title: "SHIRT STYLE!",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      title: "LOUNGEWEAR LOVE",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      title: "LIGHT JACKETS",
    },
  ];

  export const popularProducts = [
    {
      id:1,
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
      title: 'T-shirt Jake Guitar Vintage',
      desc: 'Look better than you look now',
      price: 24,
      color: 'white',
      size: 'M',
      productID: 51684618,
      shipping: 5,
    },
    {
      id:2,
      img:"https://cdn.shopify.com/s/files/1/0101/4832/products/Angela_Natural_Tee.png?v=1606780388",
      title: 'T-shirt Angela Natural Tee',
      desc: 'clothes have no gender',
      price: 30,
      color: 'white',
      size: 'M',
      productID: 54984165,
      shipping: 5,
    },
    {
      id:3,
      img:"https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
      title: 'Hawaiiana Prada',
      desc: 'go to los roques and rock this shirt',
      price: 35,
      color: 'red',
      size: 'L',
      productID: 5494118,
      shipping: 10,
    },
    {
      id:4,
      img:"https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
      title: 'Dress Palms Burda',
      desc: "i bet you'll look greate :)",
      price: 26,
      color: 'green',
      size: 'S',
      productID: 51684616,
      shipping: 5,
    },
    {
      id:5,
      img:"https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
      title: 'Eco Green Bag ',
      desc: "don't you care about the Earth?",
      price: 10,
      color: 'green',
      size: 'not available',
      productID: 549481348,
      shipping: 3,
    },
    {
      id:6,
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
      title: 'Rocket Vintage Chill Cap',
      desc: 'wear this amazing cap',
      price: 12,
      color: 'blue',
      size: 'M',
      productID: 8494651684,
      shipping: 4,
    },
    {
      id:7,
      img:"https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
      title: 'Brown Jacket Devolo Versace',
      desc: 'is it cold outside, innit?',
      price: 55,
      color: 'brown',
      size: 'L',
      productID: 8498461688,
      shipping: 2.6,
    },
  ]